-- 14. Find the total number of couriers handled by each employee
SELECT E.Name, COUNT(C.CourierID) AS TotalCouriers
FROM Employees E
LEFT JOIN Couriers C ON E.EmployeeID = C.CourierID
GROUP BY E.Name;

-- 15. Calculate the total revenue generated by each location
SELECT L.LocationName, SUM(P.Amount) AS TotalRevenue
FROM Locations L
INNER JOIN Payments P ON L.LocationID = P.LocationID
GROUP BY L.LocationName;

-- 16. Find the total number of couriers delivered to each location
SELECT L.LocationName, COUNT(P.CourierID) AS TotalCouriers
FROM Locations L
INNER JOIN Payments P ON L.LocationID = P.LocationID
GROUP BY L.LocationName;

-- 17. Find the courier with the highest average delivery time
SELECT TOP 1 CourierID, AVG(DATEDIFF(DAY, DeliveryDate, GETDATE())) AS AvgDeliveryTime
FROM Couriers
GROUP BY CourierID
ORDER BY AvgDeliveryTime DESC;

-- 18. Find locations with total payments less than a certain amount
SELECT LocationName, SUM(Amount) AS TotalPayments
FROM Locations L
INNER JOIN Payments P ON L.LocationID = P.LocationID
GROUP BY LocationName
HAVING SUM(Amount) < 500;

-- 19. Calculate total payments per location
SELECT L.LocationName, SUM(P.Amount) AS TotalPayments
FROM Locations L
INNER JOIN Payments P ON L.LocationID = P.LocationID
GROUP BY L.LocationName;

-- 20. Retrieve couriers with payments totaling more than $1000 in a specific location
SELECT C.CourierID, L.LocationName, SUM(P.Amount) AS TotalAmount
FROM Couriers C
INNER JOIN Payments P ON C.CourierID = P.CourierID
INNER JOIN Locations L ON P.LocationID = L.LocationID
GROUP BY C.CourierID, L.LocationName
HAVING SUM(P.Amount) > 1000;


--21
SELECT 
    L.LocationName, 
    SUM(P.Amount) AS TotalPayments
FROM Locations L
INNER JOIN Payments P ON L.LocationID = P.LocationID
WHERE P.PaymentDate < '2025-01-01'
GROUP BY L.LocationName
HAVING SUM(P.Amount) > 5000;


